
package datos.lab2.frame;

import java.awt.Color;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import static datos.lab2.frame.Dijstra2F3.hola;
import static datos.lab2.frame.archivo.aeropuertos;
import static datos.lab2.frame.archivo.matriz_final;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author jeffr
 */
public class data extends javax.swing.JFrame {

    archivo arch;
    public data(archivo arc) {
        initComponents();
        this.arch = arc;
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FlatAnimatedLafChange.showSnapshot();
                FlatLightLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            }
        });
        setLocationRelativeTo(null);
        setBackground(new Color(0,0,0,0));
        camino2.setEditable(false);
        adyacentes.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new datos.lab2.frame.PanelRound();
        panelRound2 = new datos.lab2.frame.PanelRound();
        buttomCustom1 = new datos.lab2.frame.ButtomCustom();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Aero1 = new javax.swing.JTextField();
        Aero2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        camino2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        Aero3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        adyacentes = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        Aero4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Info = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelRound1.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelRound2MouseDragged(evt);
            }
        });
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelRound2MousePressed(evt);
            }
        });

        buttomCustom1.setText("X");
        buttomCustom1.setBorderPainted(false);
        buttomCustom1.setEnableCustomRectangle(true);
        buttomCustom1.setFocusPainted(false);
        buttomCustom1.setFocusable(false);
        buttomCustom1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        buttomCustom1.setRoundTopRight(30);
        buttomCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttomCustom1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttomCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addComponent(buttomCustom1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1152, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setText("AEROPUERTO 1");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 46, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MINIMOS GRANDES");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 170, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelRound1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 17, 461));

        Aero1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        panelRound1.add(Aero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 77, 126, 34));

        Aero2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        panelRound1.add(Aero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 77, 126, 34));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 129, 96, 36));

        camino2.setColumns(20);
        camino2.setRows(5);
        camino2.setFocusable(false);
        jScrollPane1.setViewportView(camino2);

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 198, 328, 294));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setText("AEROPUERTO 2");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 46, 304, -1));

        Aero3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        panelRound1.add(Aero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 126, 34));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton2.setText("Enviar");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 96, 36));

        adyacentes.setColumns(20);
        adyacentes.setRows(5);
        adyacentes.setFocusable(false);
        jScrollPane2.setViewportView(adyacentes);

        panelRound1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 328, 294));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelRound1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 20, 461));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INFO AEROPUERTO");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 160, -1));

        Aero4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        panelRound1.add(Aero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, 126, 34));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jButton3.setText("Enviar");
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelRound1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 96, 36));

        Info.setColumns(20);
        Info.setRows(5);
        Info.setFocusable(false);
        jScrollPane3.setViewportView(Info);

        panelRound1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 328, 294));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelRound2MouseDragged
int x,y;
    private void panelRound2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MousePressed
       x= evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelRound2MousePressed

    private void buttomCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttomCustom1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttomCustom1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String codigo = Aero3.getText();
        int c = 0;
        for (aeropuerto i : aeropuertos) {
            if (i.codigo.equals(codigo)) {
                break;
            }
            c++;
        }
        if(c > aeropuertos.size()){
            showMessageDialog(null,"El codigo no existe");
        }
        else{
            aeropuerto[] aeropuertosV = aeropuertos.toArray(new aeropuerto[aeropuertos.size()]);
        Dijstra2F3 camino = new Dijstra2F3(matriz_final, c);
        camino.caminoMinimos();
        
        camino.si(c, aeropuertosV, matriz_final);
        adyacentes.setText("");
        adyacentes.setText(hola);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a = Aero1.getText();
        String b = Aero2.getText();
        int h = 0;
        for (aeropuerto i : aeropuertos) {
            if (i.codigo.equals(a)) {
                break;
            }
            h++; 
        }
        Dijstra2F3 camino = new Dijstra2F3(matriz_final, h);
        camino.caminoMinimos();
        String c =camino.indices_code(a, b);
        camino2.setText("");
        camino2.setText(c);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String A= Aero4.getText();
        boolean a = false;
        Info.setText("");
        for (aeropuerto i : aeropuertos){
            if (A.equals(i.codigo)) {
                Info.setText(i.mostrar_info());
                a = true;
            }
        }
        if (!a) {
            Info.setText(A + " No existe");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aero1;
    private javax.swing.JTextField Aero2;
    private javax.swing.JTextField Aero3;
    private javax.swing.JTextField Aero4;
    private javax.swing.JTextArea Info;
    private javax.swing.JTextArea adyacentes;
    private datos.lab2.frame.ButtomCustom buttomCustom1;
    private javax.swing.JTextArea camino2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private datos.lab2.frame.PanelRound panelRound1;
    private datos.lab2.frame.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
